### PR TITLE
Add info about --toggle-scan-popup command line switch

### PR DESCRIPTION
**Pull request by vedgy**
goldendict/goldendict@782cede2175f37922362015adb79da16e582602a added a new command line option --toggle-scan-popup. This commit documents the meaning and intended usage of this option in English and Russian.

Improve the English wording of related documentation and adjust the Russian translation accordingly.

Split the bottom paragraph of the "Command line switches" section into three paragraphs to improve readability.

**NOTE:** Russian is not my native language. Don't hesitate to suggest improvements to the wording of the Russian translation.

**Before:**
GD-help-14-before
**After:**
GD-help-14-after

**Before:** 
ru-GD-help-14-before

**After:** 
ru-GD-help-14-after

### CODE REVIEW

**Comment by vedgy** [comment]
The [`\c` command](https://doc.qt.io/qt-5/04-qdoc-commands-textmarkup.html#c-command) enables the code font. But unfortunately the code font doesn't differ that much from the regular font. Not sure whether replacing the quotes is a good idea.

**Comment by vedgy** [comment]
I can commit the updated generated help .qch files into goldendict master, but would be less risky if you do that. There is a chance that my system breaks some formatting, e.g. due to the Windows line endings in the help source files or due to the Qt 4 and Qt 5 mix on my system.

**Comment by vedgy** [comment]
Or maybe it'd be better not to update the binary .qch files in the goldendict repository just yet. I plan to document the recently added goldendict:// and dict:// URL scheme support; implement and document yet another often requested command line option: `--help`.

**Comment by Abs62** [comment]
OK, I'll be waiting for update.

**Pull request merged**
